# Generated by Django 5.1.1 on 2024-09-15 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_management', '0002_alter_subject_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name_plural': 'Campuses'},
        ),
    ]
