# Generated by Django 5.1.1 on 2024-09-15 04:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_management', '0004_fileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='link',
        ),
        migrations.AddField(
            model_name='chapter',
            name='levels',
            field=models.ManyToManyField(to='campus_management.level'),
        ),
    ]
