# Generated by Django 5.1.1 on 2024-09-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_management', '0005_level_remove_chapter_link_chapter_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='link',
        ),
        migrations.RemoveField(
            model_name='level',
            name='name',
        ),
        migrations.AlterField(
            model_name='level',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
