# Generated by Django 5.1.1 on 2024-09-15 15:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('pdflink', models.URLField()),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('levels', models.ManyToManyField(related_name='chapters', to='content_management.level')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.URLField()),
                ('chapters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='content_management.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.URLField()),
                ('description', models.TextField()),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='content_management.subject')),
            ],
            options={
                'verbose_name_plural': 'Campuses',
            },
        ),
    ]
