# Generated by Django 5.1.1 on 2024-09-27 07:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campus_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.URLField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Campuses',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapter_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='content_management.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.URLField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='content_management.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson_code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_done', models.BooleanField(default=False)),
                ('objective', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('specific_learning_outcome', models.TextField(blank=True, null=True)),
                ('behavioural_outcome', models.TextField(blank=True, null=True)),
                ('materials_required', models.TextField(blank=True, null=True)),
                ('activate', models.JSONField(blank=True, null=True)),
                ('acquire', models.JSONField(blank=True, null=True)),
                ('apply', models.JSONField(blank=True, null=True)),
                ('assess', models.JSONField(blank=True, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content_management.chapter')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content_management.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content_management.subject')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='content_management.subject'),
        ),
    ]
