# Generated by Django 5.1.1 on 2024-09-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_code', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=100)),
                ('objective', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('specific_learning_outcome', models.TextField()),
                ('behavioural_outcome', models.TextField()),
                ('materials_required', models.TextField()),
                ('hook', models.TextField()),
                ('assess', models.TextField()),
                ('inform', models.TextField()),
            ],
        ),
    ]
